// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/module-welcome/MilestoneMap.tsx": () => import("../components/mockups/module-welcome/MilestoneMap.tsx"),
  "./components/mockups/module-welcome/MissionBrief.tsx": () => import("../components/mockups/module-welcome/MissionBrief.tsx"),
  "./components/mockups/module-welcome/ZeroChrome.tsx": () => import("../components/mockups/module-welcome/ZeroChrome.tsx")
};
